### ISSUE TITLE
this works but..

### ISSUE THREAD

**Issue by crawlingcity** [scriptsingh/plex_av1_tvos#2]
Model: Apple TV 4K (3rd Gen, A2843)

I wanted to ask, do you have any issues with this profile?

After creating the profiles folder and putting the file there, I can confirm it does direct play, but it takes 30-60+ seconds to open the media file, sometimes more. 

After it opens, it's incredible fast to move forward/backward, but all this time opening the file, doesn't seem normal.

Am I alone here?

I prefer plex's UI, but I guess Jellyfin is the way, I can direct play anything without any issue (not wanting to start a debate here :D)

**Comment by joey-suri** [comment]
I’m not having any issues with the profile causing files to load slow.

**Comment by crawlingcity** [comment]
trace it to a problem in my current homelab. I'm running plex on k3s and "something" is causing the lag. moving plex server outside the k3s works flawlessly. closing.
